
<option value="Imágenes">Imágenes</option>
<option></option>
<option value="Cardiología">Cardiología</option>
<option value="Cirugía cardiovascular">Cirugía cardiovascular</option>
<option value="Cirugía plástica">Cirugía plástica</option>
<option value="Cirugía general">Cirugía general</option>
<option value="Cirugía bariátrica y metabólica">Cirugía bariátrica y metabólica</option>
<option value="Cirugía oncológica">Cirugía oncológica</option>
<option value="Cirugía pediátrica">Cirugía pediátrica</option>
<option value="Dermatología">Dermatología</option>
<option value="Ecografía obstétrica">Ecografía obstétrica</option>
<option value="Endocrinología">Endocrinología</option>
<option value="Flebología y linfología">Flebología y linfología</option>
<option value="Gastroenterología">Gastroenterología</option>
<option value="Ginecología y obstetricia">Ginecología y obstetricia</option>
<option value="Inmunología y reumatología">Inmunología y Reumatología</option>
<option value="Médicos de guardía">Médicos de guardía</option>
<option value="Neumología">Neumología</option>
<option value="Neurología">Neurología</option>
<option value="Nutrición">Nutrición</option>
<option value="Oftalmología">Oftalmología</option>
<option value="Otorrinolaringologia">Otorrinolaringología</option>
<option value="Oncología - Mastologia">Oncología Mastología</option>
<option value="Oncología Molecular">Oncología Molecular</option>
<option value="Pediatría">Pediatría</option>
<option value="Psicología">Psicología</option>
<option value="Radiología">Radiología</option>
<option value="Reumatología">Reumatología</option>
<option value="Traumatología">Traumatología</option>
<option value="Terapia del dolor">Terapia del dolor</option>
<option value="Urología">Urología</option>
<option value="Zerenia">Zerenia</option>